version: '3'

services:

  zookeeper:
    image: zookeeper
    volumes:
      - './data/zoo/data:/data'
      - './data/zoo/datalog:/datalog'

  ch1:
    image: yandex/clickhouse-server:18.16.1
    restart: on-failure
    depends_on:
      - zookeeper
    volumes:
      - './data/ch1/ch:/var/lib/clickhouse/'
      - './ch_configs_ch1:/etc/clickhouse-server/'
      - './dictionaries:/opt/dictionaries/'
    ports:
      - 9000:9000
      - 8123:8123
      - 9440:9440
      - 8443:8443
    ulimits:
      nofile: 262144

  ch2:
    image: yandex/clickhouse-server:18.16.1
    restart: on-failure
    depends_on:
      - zookeeper
    volumes:
      - './data/ch2/ch:/var/lib/clickhouse/'
      - './ch_configs_ch2:/etc/clickhouse-server/'
      - './dictionaries:/opt/dictionaries/'
    ulimits:
      nofile: 262144

  ch3:
    image: yandex/clickhouse-server:18.16.1
    restart: on-failure
    depends_on:
      - zookeeper
    volumes:
      - './data/ch3/ch:/var/lib/clickhouse/'
      - './ch_configs_ch3:/etc/clickhouse-server/'
      - './dictionaries:/opt/dictionaries/'
    ulimits:
      nofile: 262144

  ch4:
    image: yandex/clickhouse-server:18.16.1
    restart: on-failure
    depends_on:
      - zookeeper
    volumes:
      - './data/ch4/ch:/var/lib/clickhouse/'
      - './ch_configs_ch4:/etc/clickhouse-server/'
      - './dictionaries:/opt/dictionaries/'
    ulimits:
      nofile: 262144

  client:
    image: yandex/clickhouse-client:18.16.1
    volumes:
      - './client-config.xml:/etc/clickhouse-client/config.xml'