version: '3'

services:
  ch:
    image: yandex/clickhouse-server:18.14.15
    restart: on-failure
    volumes:
      - './data/ch:/var/lib/clickhouse/'
    ports:
      - 9000:9000
      - 8123:8123
    ulimits:
      nofile: 262144
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
#        reservations:
#          cpus: '0.1'
#          memory: 256M
    
  client:
    image: yandex/clickhouse-client:18.14.15